### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by Miserlou** [bowmanjd/geeseflypy#2]
I'd love to use Geesflypy in [omnihash](https://github.com/Miserlou/omnihash/issues/4), as this is the only P2.7 compatible Skein implementation I've found, but it isn't available on PyPI.

Would you be willing to publish GFP to PyPI? I realize that it's probably been a while since you touched this code. I'm also happy to publish and maintain it, if that's ok.

**Comment by bowmanjd** [comment]
Sorry I have thoroughly neglected this project (and hence did not notice your comment years ago. I'd be embarrassed to publish this to PyPI, as it is abandoned, more or less. If you want to take it on, be my guest.
